model = "meta-llama/Llama-3.2-3B-Instruct"
env_file = ["secrets.env"]
max_steps = 500

batch_size = 512
rollouts_per_example = 16
learning_rate = 1e-6

[sampling]
max_tokens = 256
temperature = 0.7

[[env]]
id = "michaelginn/translation-cycles"
args = { target_lang = "deu_Latn", num_sentences = 10000 }

[eval]
interval = 100
num_examples = -1
rollouts_per_example = 1
eval_base_model = true

[[eval.env]]
name = "flores-forward"
id = "michaelginn/flores-eval"
args = { target_lang = "deu_Latn", direction = "forward" }

[[eval.env]]
name = "flores-backward"
id = "michaelginn/flores-eval"
args = { target_lang = "deu_Latn", direction = "backward" }

[wandb]
project = "rl-translation-cycles-prime"
entity = "lecs-general"

[checkpoints]
interval = 100
keep_cloud = 3

[infrastructure]
compute_size = "L"
